webtalk_init -webtalk_dir /home/010/a/ax/axk200011/Micro_Design/Micro_Design.sim/sim_1/behav/xsim/xsim.dir/tb_muxc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 14 15:49:22 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eb566020-8c29-4555-9140-3ef51e5fbf4d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "acd5335ed4f44d7b83c4b48785c0f766" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 7.9 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7F32 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3692.981 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "269.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128680_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2603040348 -regid "" -xml /home/010/a/ax/axk200011/Micro_Design/Micro_Design.sim/sim_1/behav/xsim/xsim.dir/tb_muxc_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/010/a/ax/axk200011/Micro_Design/Micro_Design.sim/sim_1/behav/xsim/xsim.dir/tb_muxc_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/010/a/ax/axk200011/Micro_Design/Micro_Design.sim/sim_1/behav/xsim/xsim.dir/tb_muxc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
